# Generated by Django 3.2.16 on 2022-10-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenExchangeConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        help_text="Specifies the scope/audience, so that Keycloak knows which sort of access token to return.",
                        max_length=250,
                        verbose_name="audience",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="Keycloak client ID.",
                        max_length=250,
                        verbose_name="client ID",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Keycloak secret for the client ID specified.",
                        max_length=250,
                        verbose_name="secret",
                    ),
                ),
                (
                    "discovery_endpoint",
                    models.URLField(
                        help_text="URL of your OpenID Connect provider discovery endpoint ending with a slash (`.well-known/...` will be added automatically). If this is provided, the remaining endpoints can be omitted, as they will be derived from this endpoint.",
                        verbose_name="discovery endpoint",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        help_text="External API service",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token exchange plugin configuration",
            },
        ),
    ]
