version: '3.4'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db:/var/lib/postgresql/data

  test:
    build:
      context: .
      args:
        RELEASE: ${TAG:-latest}
        SDK_RELEASE: ${SDK_TAG:-latest}
    image: open-forms-ext-token-exchange:test
    environment:
      - DJANGO_SETTINGS_MODULE=openforms.conf.docker
      - SECRET_KEY=${SECRET_KEY:-@r0w-0(&apjfde5fl6h23!vn)r1ldkp1c_d2#!$$did4z5hun4a}
      - OPEN_FORMS_EXTENSIONS=token_exchange
      - DB_NAME=openforms
      - DB_USER=openforms
      - DB_HOST=db
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - CACHE_OIDC=redis:6379/0
      - CACHE_PORTALOCKER=redis:6379/0
      - ALLOWED_HOSTS=*
      - CORS_ALLOW_ALL_ORIGINS=yes
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_LOGLEVEL=DEBUG
      - SDK_BASE_URL=${SDK_BASE_URL:-http://localhost:8001}
      - OPENFORMS_LOCATION_CLIENT=${OPENFORMS_LOCATION_CLIENT:-openforms.contrib.bag.client.BAGClient}
      - TWO_FACTOR_FORCE_OTP_ADMIN=0
      - TWO_FACTOR_PATCH_ADMIN=0
      # Needed for Celery Flower to match the TIME_ZONE configured in the
      # settings used by workers and beat containers.
      - TZ=Europe/Amsterdam
    command: /test.sh
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db:
