name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 4 * * *'

permissions: {}

env:
  IMAGE_NAME: openformulieren/open-forms-ext-token-exchange

jobs:
  tests:
    name: Run the Django test suite
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          --name postgres
      redis:
        image: redis:8
        ports:
          - 6379:6379

    steps:
      - name: Checkout Open Forms
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: open-formulieren/open-forms
          path: open-forms
          persist-credentials: 'false'

      - name: Checkout Token Exchange extension
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: extension
          persist-credentials: 'false'

      - name: Set up backend environment
        uses: maykinmedia/setup-django-backend@1a27eae04b1ec4d1250ed720e29fefd3508cb4c6 # v1.4.1
        with:
          apt-packages: 'libxml2 libxmlsec1 libxmlsec1-openssl gettext postgresql-client gdal-bin'
          python-version: '3.12'
          optimize-postgres: 'yes'
          pg-service: 'postgres'
          setup-node: 'yes'
          nvmrc-custom-dir: 'open-forms'
          working-directory: ${{ github.workspace }}/open-forms

      - name: Make symlink in OF to the extension
        run: |
          ln -s ${{ github.workspace }}/extension/token_exchange ${{ github.workspace }}/open-forms/src

      - name: Run tests
        run: |
          export OPEN_FORMS_EXTENSIONS=token_exchange

          python src/manage.py compilemessages
          coverage run --source=token_exchange src/manage.py test token_exchange
          coverage combine
          coverage xml -o coverage-extension.xml
        env:
          DJANGO_SETTINGS_MODULE: openforms.conf.ci
          SECRET_KEY: dummy
          DB_USER: postgres
          DB_PASSWORD: ''
        working-directory: ${{ github.workspace }}/open-forms

      - name: Publish coverage report
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          root_dir: ${{ github.workspace }}/extension
          working-directory: ${{ github.workspace }}/open-forms
          files: ./coverage-extension.xml

  docker_build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: 'false'
      - name: Build the Docker image
        run: docker build .

  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    needs:
      - tests
      - docker_build

    environment: release
    permissions:
      id-token: write

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: 'false'
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'

      - name: Build sdist and wheel
        run: |
          pip install build --upgrade
          python -m build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
